// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus.LAS.Identity.IdentityDbContext;

#nullable disable

namespace Nexus.LAS.Identity.Migrations
{
    [DbContext(typeof(NexusLASIdentityDbContext))]
    partial class NexusLASIdentityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nexus.LAS.Domain.Entities.UserGroupEntities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedBy_Date");

                    b.Property<int>("CreatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy_IDN");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy_Name");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LoginName");

                    b.Property<string>("NTLogin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NTLogin");

                    b.Property<int?>("PersonsIdN")
                        .HasColumnType("int")
                        .HasColumnName("Persons_IDN");

                    b.Property<DateTime?>("UpdatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedBy_Date");

                    b.Property<int?>("UpdatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("UpdatedBy_IDN");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy_Name");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Nexus.LAS.Domain.Entities.UserGroupEntities.UserGroup", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId")
                        .HasColumnOrder(0);

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("GroupId")
                        .HasColumnOrder(1);

                    b.HasKey("UserId", "GroupId");

                    b.ToTable("UserGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
