// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nexus.LAS.Persistence.DatabaseContext;

#nullable disable

namespace Nexus.LAS.Persistence.Migrations
{
    [DbContext(typeof(NexusLASDbContext))]
    [Migration("20250707211635_company-create")]
    partial class companycreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nexus.LAS.Domain.Entities.CompanyEntities.CompaniesAccountSignatory", b =>
                {
                    b.Property<int>("CompaniesAccountSignatoryIdn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CompaniesAccountSignatoryIDN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompaniesAccountSignatoryIdn"));

                    b.Property<bool?>("AccountSignatoryActive")
                        .HasColumnType("bit")
                        .HasColumnName("AccountSignatoryActive");

                    b.Property<DateTime?>("AccountSignatoryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("AccountSignatoryDate");

                    b.Property<int>("AccountSignatoryPersonIdn")
                        .HasColumnType("int")
                        .HasColumnName("AccountSignatoryPerson_IDN");

                    b.Property<string>("AccountSignatoryRule")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AccountSignatoryRule");

                    b.Property<string>("CompaniesAccountSignatoryIdc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CompaniesAccountSignatoryIDC");

                    b.Property<int>("CompaniesBankAccountIdn")
                        .HasColumnType("int")
                        .HasColumnName("CompaniesBankAccount_IDN");

                    b.Property<DateTime>("CreatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedBy_Date");

                    b.Property<int>("CreatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy_IDN");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy_Name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<long>("FromAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("FromAmount");

                    b.Property<long>("ToAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("ToAmount");

                    b.Property<DateTime?>("UpdatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedBy_Date");

                    b.Property<int?>("UpdatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("UpdatedBy_IDN");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy_Name");

                    b.HasKey("CompaniesAccountSignatoryIdn");

                    b.ToTable("CompaniesAccountSignatory");
                });

            modelBuilder.Entity("Nexus.LAS.Domain.Entities.CompanyEntities.CompaniesActivities", b =>
                {
                    b.Property<int>("CompaniesActivityIdn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CompaniesActivityIDN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompaniesActivityIdn"));

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Activity");

                    b.Property<string>("CompaniesActivityIdc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CompaniesActivityIDC");

                    b.Property<int>("CompaniesIdn")
                        .HasColumnType("int")
                        .HasColumnName("Companies_IDN");

                    b.Property<DateTime>("CreatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedBy_Date");

                    b.Property<int>("CreatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy_IDN");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy_Name");

                    b.Property<DateTime?>("UpdatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedBy_Date");

                    b.Property<int?>("UpdatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("UpdatedBy_IDN");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy_Name");

                    b.HasKey("CompaniesActivityIdn");

                    b.ToTable("CompaniesActivities");
                });

            modelBuilder.Entity("Nexus.LAS.Domain.Entities.CompanyEntities.CompaniesAddress", b =>
                {
                    b.Property<int>("CompaniesAddressIdn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CompaniesAddressIDN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompaniesAddressIdn"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AddressLine1");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AddressLine2");

                    b.Property<string>("AddressLine3")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AddressLine3");

                    b.Property<bool>("AddressPrimary")
                        .HasColumnType("bit")
                        .HasColumnName("AddressPrimary");

                    b.Property<string>("CompaniesAddressIdc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CompaniesAddressIDC");

                    b.Property<int>("CompaniesIdn")
                        .HasColumnType("int")
                        .HasColumnName("Companies_IDN");

                    b.Property<DateTime>("CreatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedBy_Date");

                    b.Property<int>("CreatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy_IDN");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy_Name");

                    b.Property<string>("PoBoxCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("POBoxCity");

                    b.Property<string>("PoBoxCountry")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("POBoxCountry");

                    b.Property<string>("PoBoxNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("POBoxumber");

                    b.Property<DateTime?>("UpdatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedBy_Date");

                    b.Property<int?>("UpdatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("UpdatedBy_IDN");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy_Name");

                    b.HasKey("CompaniesAddressIdn");

                    b.ToTable("CompaniesAddresses");
                });

            modelBuilder.Entity("Nexus.LAS.Domain.Entities.CompanyEntities.CompaniesAuthorizedSignatory", b =>
                {
                    b.Property<int>("CompaniesAuthorizedSignatoryIdn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CompaniesAuthorizedSignatoryIDN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompaniesAuthorizedSignatoryIdn"));

                    b.Property<string>("CompaniesAuthorizedSignatoryIdc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CompaniesAuthorizedSignatoryIDC");

                    b.Property<int>("CompaniesIdn")
                        .HasColumnType("int")
                        .HasColumnName("Companies_IDN");

                    b.Property<DateTime>("CreatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedBy_Date");

                    b.Property<int>("CreatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy_IDN");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy_Name");

                    b.Property<int?>("PersonsIdn")
                        .HasColumnType("int")
                        .HasColumnName("Persons_IDN");

                    b.Property<string>("PoaType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("POAType");

                    b.Property<string>("PoaTypeDetails")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("POATypeDetails");

                    b.Property<DateTime?>("UpdatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedBy_Date");

                    b.Property<int?>("UpdatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("UpdatedBy_IDN");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy_Name");

                    b.HasKey("CompaniesAuthorizedSignatoryIdn");

                    b.ToTable("CompaniesAuthorizedSignatories");
                });

            modelBuilder.Entity("Nexus.LAS.Domain.Entities.CompanyEntities.CompaniesBankAccount", b =>
                {
                    b.Property<int>("CompaniesBankAccountIdn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CompaniesBankAccountIDN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompaniesBankAccountIdn"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AccountNumber");

                    b.Property<bool>("BankAccountActive")
                        .HasColumnType("bit")
                        .HasColumnName("BankAccountActive");

                    b.Property<DateTime>("BankAccountDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("BankAccountDate");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("BankName");

                    b.Property<string>("CompaniesBankAccountIdc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CompaniesBankAccountIDC");

                    b.Property<int>("CompaniesIdn")
                        .HasColumnType("int")
                        .HasColumnName("Companies_IDN");

                    b.Property<DateTime>("CreatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedBy_Date");

                    b.Property<int>("CreatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy_IDN");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy_Name");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Note");

                    b.Property<DateTime?>("UpdatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedBy_Date");

                    b.Property<int?>("UpdatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("UpdatedBy_IDN");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy_Name");

                    b.HasKey("CompaniesBankAccountIdn");

                    b.ToTable("CompaniesBankAccount");
                });

            modelBuilder.Entity("Nexus.LAS.Domain.Entities.CompanyEntities.CompaniesBoard", b =>
                {
                    b.Property<int>("CompaniesBoardIdn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CompaniesBoardIDN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompaniesBoardIdn"));

                    b.Property<bool>("BoardActive")
                        .HasColumnType("bit")
                        .HasColumnName("BoardActive");

                    b.Property<DateTime>("BoardDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("BoardDate");

                    b.Property<string>("CompaniesBoardIdc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CompaniesBoardIDC");

                    b.Property<int>("CompaniesIdn")
                        .HasColumnType("int")
                        .HasColumnName("Companies_IDN");

                    b.Property<DateTime>("CreatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedBy_Date");

                    b.Property<int>("CreatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy_IDN");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy_Name");

                    b.Property<DateTime?>("UpdatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedBy_Date");

                    b.Property<int?>("UpdatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("UpdatedBy_IDN");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy_Name");

                    b.HasKey("CompaniesBoardIdn");

                    b.ToTable("CompaniesBoards");
                });

            modelBuilder.Entity("Nexus.LAS.Domain.Entities.CompanyEntities.CompaniesBoardMember", b =>
                {
                    b.Property<int>("CompaniesBoardMemberIdn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CompaniesBoardMemberIDN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompaniesBoardMemberIdn"));

                    b.Property<bool?>("BoardMemberActive")
                        .HasColumnType("bit")
                        .HasColumnName("BoardMemberActive");

                    b.Property<string>("BoardMemberPosition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("BoardMemberPosition");

                    b.Property<string>("CompaniesBoardMemberIdc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CompaniesBoardMemberIDC");

                    b.Property<int?>("CompaniesBoardsIdn")
                        .HasColumnType("int")
                        .HasColumnName("CompaniesBoards_IDN");

                    b.Property<DateTime>("CreatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedBy_Date");

                    b.Property<int>("CreatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy_IDN");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy_Name");

                    b.Property<int>("PersonIdn")
                        .HasColumnType("int")
                        .HasColumnName("Person_IDN");

                    b.Property<DateTime?>("UpdatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedBy_Date");

                    b.Property<int?>("UpdatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("UpdatedBy_IDN");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy_Name");

                    b.HasKey("CompaniesBoardMemberIdn");

                    b.ToTable("CompaniesBoardMembers");
                });

            modelBuilder.Entity("Nexus.LAS.Domain.Entities.CompanyEntities.CompaniesCapital", b =>
                {
                    b.Property<int>("CompaniesCapitalIdn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CompaniesCapitalIDN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompaniesCapitalIdn"));

                    b.Property<bool>("CompaniesCapitalActive")
                        .HasColumnType("bit")
                        .HasColumnName("CompaniesCapitalActive");

                    b.Property<double?>("CompaniesCapitalAmount")
                        .HasColumnType("float")
                        .HasColumnName("CompaniesCapitalAmount");

                    b.Property<double?>("CompaniesCapitalAuthorized")
                        .HasColumnType("float")
                        .HasColumnName("CompaniesCapitalAuthorized");

                    b.Property<string>("CompaniesCapitalCurrency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CompaniesCapitalCurrency");

                    b.Property<DateTime?>("CompaniesCapitalDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CompaniesCapitalDate");

                    b.Property<string>("CompaniesCapitalIdc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CompaniesCapitalIDC");

                    b.Property<long?>("CompaniesCapitalIssuedShares")
                        .HasColumnType("bigint")
                        .HasColumnName("CompaniesCapitalIssuedShares");

                    b.Property<long?>("CompaniesCapitalNumberOfShares")
                        .HasColumnType("bigint")
                        .HasColumnName("CompaniesCapitalNumberOfShares");

                    b.Property<double?>("CompaniesCapitalPaid")
                        .HasColumnType("float")
                        .HasColumnName("CompaniesCapitalPaid");

                    b.Property<int>("CompaniesIdn")
                        .HasColumnType("int")
                        .HasColumnName("Companies_IDN");

                    b.Property<DateTime>("CreatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedBy_Date");

                    b.Property<int>("CreatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy_IDN");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy_Name");

                    b.Property<DateTime?>("UpdatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedBy_Date");

                    b.Property<int?>("UpdatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("UpdatedBy_IDN");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy_Name");

                    b.HasKey("CompaniesCapitalIdn");

                    b.ToTable("CompaniesCapitals");
                });

            modelBuilder.Entity("Nexus.LAS.Domain.Entities.CompanyEntities.CompaniesChamberOfCommerce", b =>
                {
                    b.Property<int>("CompaniesChamberOfCommerceIdn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CompaniesChamberOfCommerceIDN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompaniesChamberOfCommerceIdn"));

                    b.Property<bool?>("CciExpiryActiveReminder")
                        .HasColumnType("bit")
                        .HasColumnName("CCIExpiryActiveReminder");

                    b.Property<DateTime?>("CciExpiryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CCIExpiryDate");

                    b.Property<DateTime>("CciIssueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CCIIssueDate");

                    b.Property<string>("CciNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CCINumber");

                    b.Property<string>("CciPassword")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CCIPassword");

                    b.Property<string>("CciUsername")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CCIUsername");

                    b.Property<string>("CompaniesChamberOfCommerceIdc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CompaniesChamberOfCommerceIDC");

                    b.Property<int>("CompaniesIdn")
                        .HasColumnType("int")
                        .HasColumnName("Companies_IDN");

                    b.Property<DateTime>("CreatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedBy_Date");

                    b.Property<int>("CreatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy_IDN");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy_Name");

                    b.Property<DateTime?>("UpdatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedBy_Date");

                    b.Property<int?>("UpdatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("UpdatedBy_IDN");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy_Name");

                    b.HasKey("CompaniesChamberOfCommerceIdn");

                    b.ToTable("CompaniesChamberOfCommerces");
                });

            modelBuilder.Entity("Nexus.LAS.Domain.Entities.CompanyEntities.CompaniesContract", b =>
                {
                    b.Property<int>("CompaniesContractIdn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CompaniesContractIDN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompaniesContractIdn"));

                    b.Property<DateTime?>("CommencementDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CommencementDate");

                    b.Property<string>("CompaniesContractIdc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CompaniesContractIDC");

                    b.Property<int>("CompaniesIdn")
                        .HasColumnType("int")
                        .HasColumnName("Companies_IDN");

                    b.Property<string>("ContractDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ContractDescription");

                    b.Property<bool?>("ContractExpiryActiveReminder")
                        .HasColumnType("bit")
                        .HasColumnName("ContractExpiryActiveReminder");

                    b.Property<DateTime?>("ContractExpiryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ContractExpiryDate");

                    b.Property<string>("ContractStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ContractStatus");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ContractType");

                    b.Property<DateTime>("CreatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedBy_Date");

                    b.Property<int>("CreatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy_IDN");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy_Name");

                    b.Property<DateTime?>("DocumentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DocumentDate");

                    b.Property<DateTime?>("UpdatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedBy_Date");

                    b.Property<int?>("UpdatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("UpdatedBy_IDN");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy_Name");

                    b.HasKey("CompaniesContractIdn");

                    b.ToTable("CompaniesContracts");
                });

            modelBuilder.Entity("Nexus.LAS.Domain.Entities.CompanyEntities.CompaniesEmail", b =>
                {
                    b.Property<int>("CompaniesEmailIdn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CompaniesEmailIDN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompaniesEmailIdn"));

                    b.Property<string>("CompaniesEmailIdc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CompaniesEmailIDC");

                    b.Property<int>("CompaniesIdn")
                        .HasColumnType("int")
                        .HasColumnName("Companies_IDN");

                    b.Property<DateTime>("CreatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedBy_Date");

                    b.Property<int>("CreatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy_IDN");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy_Name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Email");

                    b.Property<bool>("EmailPrimary")
                        .HasColumnType("bit")
                        .HasColumnName("EmailPrimary");

                    b.Property<DateTime?>("UpdatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedBy_Date");

                    b.Property<int?>("UpdatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("UpdatedBy_IDN");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy_Name");

                    b.HasKey("CompaniesEmailIdn");

                    b.ToTable("CompaniesEmails");
                });

            modelBuilder.Entity("Nexus.LAS.Domain.Entities.CompanyEntities.CompaniesLeaseContract", b =>
                {
                    b.Property<int>("CompaniesLeaseContractIdn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CompaniesLeaseContractIDN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompaniesLeaseContractIdn"));

                    b.Property<DateTime?>("CommencementDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CommencementDate");

                    b.Property<int>("CompaniesIdn")
                        .HasColumnType("int")
                        .HasColumnName("Companies_IDN");

                    b.Property<string>("CompaniesLeaseContractIdc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CompaniesLeaseContractIDC");

                    b.Property<DateTime>("CreatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedBy_Date");

                    b.Property<int>("CreatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy_IDN");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy_Name");

                    b.Property<bool?>("LeaseContractExpiryActiveReminder")
                        .HasColumnType("bit")
                        .HasColumnName("LeaseContractExpiryActiveReminder");

                    b.Property<DateTime?>("LeaseContractExpiryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("LeaseContractExpiryDate");

                    b.Property<DateTime?>("UpdatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedBy_Date");

                    b.Property<int?>("UpdatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("UpdatedBy_IDN");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy_Name");

                    b.HasKey("CompaniesLeaseContractIdn");

                    b.ToTable("CompaniesLeaseContracts");
                });

            modelBuilder.Entity("Nexus.LAS.Domain.Entities.CompanyEntities.CompaniesLeaseContractRegister", b =>
                {
                    b.Property<int>("CompaniesLeaseContractsIdn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CompaniesLeaseContracts_IDN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompaniesLeaseContractsIdn"));

                    b.Property<DateTime>("CreatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedBy_Date");

                    b.Property<int>("CreatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy_IDN");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy_Name");

                    b.Property<string>("LeaseRegistersIdc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LeaseRegisters_IDC");

                    b.Property<int>("LeaseRegistersIdn")
                        .HasColumnType("int")
                        .HasColumnName("LeaseRegisters_IDN");

                    b.Property<DateTime?>("UpdatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedBy_Date");

                    b.Property<int?>("UpdatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("UpdatedBy_IDN");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy_Name");

                    b.HasKey("CompaniesLeaseContractsIdn");

                    b.ToTable("CompaniesLeaseContractRegisters");
                });

            modelBuilder.Entity("Nexus.LAS.Domain.Entities.CompanyEntities.CompaniesLicense", b =>
                {
                    b.Property<int>("CompaniesLicenseIdn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CompaniesLicenseIDN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompaniesLicenseIdn"));

                    b.Property<int>("CompaniesIdn")
                        .HasColumnType("int")
                        .HasColumnName("Companies_IDN");

                    b.Property<string>("CompaniesLicenseIdc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CompaniesLicenseIDC");

                    b.Property<DateTime>("CreatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedBy_Date");

                    b.Property<int>("CreatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy_IDN");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy_Name");

                    b.Property<string>("LicenseClassification")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LicenseClassification");

                    b.Property<bool?>("LicenseExpiryActiveReminder")
                        .HasColumnType("bit")
                        .HasColumnName("LicenseExpiryActiveReminder");

                    b.Property<DateTime?>("LicenseExpiryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("LicenseExpiryDate");

                    b.Property<DateTime>("LicenseIssueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("LicenseIssueDate");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LicenseNumber");

                    b.Property<bool>("LicensePrimary")
                        .HasColumnType("bit")
                        .HasColumnName("LicensePrimary");

                    b.Property<string>("LicenseStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LicenseStatus");

                    b.Property<DateTime?>("UpdatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedBy_Date");

                    b.Property<int?>("UpdatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("UpdatedBy_IDN");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy_Name");

                    b.HasKey("CompaniesLicenseIdn");

                    b.ToTable("CompaniesLicenses");
                });

            modelBuilder.Entity("Nexus.LAS.Domain.Entities.CompanyEntities.CompaniesOtherContract", b =>
                {
                    b.Property<int>("CompaniesOtherContractIdn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CompaniesOtherContractIDN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompaniesOtherContractIdn"));

                    b.Property<int>("CompaniesIdn")
                        .HasColumnType("int")
                        .HasColumnName("Companies_IDN");

                    b.Property<string>("CompaniesOtherContractIdc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CompaniesOtherContractIDC");

                    b.Property<DateTime?>("ContractDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ContractDate");

                    b.Property<string>("ContractDescription")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("ContractDescription");

                    b.Property<DateTime>("CreatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedBy_Date");

                    b.Property<int>("CreatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy_IDN");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy_Name");

                    b.Property<DateTime?>("UpdatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedBy_Date");

                    b.Property<int?>("UpdatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("UpdatedBy_IDN");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy_Name");

                    b.HasKey("CompaniesOtherContractIdn");

                    b.ToTable("CompaniesOtherContracts");
                });

            modelBuilder.Entity("Nexus.LAS.Domain.Entities.CompanyEntities.CompaniesPersonInCharge", b =>
                {
                    b.Property<int>("CompaniesPersonInChargeIdn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CompaniesPersonInChargeIDN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompaniesPersonInChargeIdn"));

                    b.Property<int>("CompaniesIdn")
                        .HasColumnType("int")
                        .HasColumnName("Companies_IDN");

                    b.Property<string>("CompaniesPersonInChargeIdc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CompaniesPersonInChargeIDC");

                    b.Property<DateTime>("CreatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedBy_Date");

                    b.Property<int>("CreatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy_IDN");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy_Name");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Designation");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("Notes");

                    b.Property<bool?>("PersonInChargeActive")
                        .HasColumnType("bit")
                        .HasColumnName("PersonInChargeActive");

                    b.Property<DateTime?>("PersonInChargeDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("PersonInChargeDate");

                    b.Property<int>("PersonsIdn")
                        .HasColumnType("int")
                        .HasColumnName("Persons_IDN");

                    b.Property<DateTime?>("UpdatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedBy_Date");

                    b.Property<int?>("UpdatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("UpdatedBy_IDN");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy_Name");

                    b.HasKey("CompaniesPersonInChargeIdn");

                    b.ToTable("CompaniesPersonInCharges");
                });

            modelBuilder.Entity("Nexus.LAS.Domain.Entities.CompanyEntities.CompaniesPhone", b =>
                {
                    b.Property<int>("CompaniesPhoneIdn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CompaniesPhoneIDN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompaniesPhoneIdn"));

                    b.Property<int?>("CompaniesIdn")
                        .HasColumnType("int")
                        .HasColumnName("Companies_IDN");

                    b.Property<string>("CompaniesPhoneIdc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CompaniesPhoneIDC");

                    b.Property<DateTime>("CreatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedBy_Date");

                    b.Property<int>("CreatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy_IDN");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy_Name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PhoneNumber");

                    b.Property<bool?>("PhonePrimary")
                        .HasColumnType("bit")
                        .HasColumnName("PhonePrimary");

                    b.Property<string>("PhoneType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PhoneType");

                    b.Property<DateTime?>("UpdatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedBy_Date");

                    b.Property<int?>("UpdatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("UpdatedBy_IDN");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy_Name");

                    b.HasKey("CompaniesPhoneIdn");

                    b.ToTable("CompaniesPhones");
                });

            modelBuilder.Entity("Nexus.LAS.Domain.Entities.CompanyEntities.CompaniesShareHolder", b =>
                {
                    b.Property<int>("CompaniesShareHolderIdn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CompaniesShareHolderIDN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompaniesShareHolderIdn"));

                    b.Property<string>("CompaniesShareHolderIdc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CompaniesShareHolderIDC");

                    b.Property<int?>("CompaniesShareHoldersGroupsIdn")
                        .HasColumnType("int")
                        .HasColumnName("CompaniesShareHoldersGroups_IDN");

                    b.Property<DateTime>("CreatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedBy_Date");

                    b.Property<int>("CreatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy_IDN");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy_Name");

                    b.Property<string>("RegistersIdc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Registers_IDC");

                    b.Property<int>("RegistersIdn")
                        .HasColumnType("int")
                        .HasColumnName("Registers_IDN");

                    b.Property<bool?>("ShareHolderActive")
                        .HasColumnType("bit")
                        .HasColumnName("ShareHolderActive");

                    b.Property<DateTime?>("ShareHolderDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ShareHolderDate");

                    b.Property<long?>("ShareHolderNumbersOfShares")
                        .HasColumnType("bigint")
                        .HasColumnName("ShareHolderNumbersOfShares");

                    b.Property<DateTime?>("UpdatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedBy_Date");

                    b.Property<int?>("UpdatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("UpdatedBy_IDN");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy_Name");

                    b.HasKey("CompaniesShareHolderIdn");

                    b.ToTable("CompaniesShareHolders");
                });

            modelBuilder.Entity("Nexus.LAS.Domain.Entities.CompanyEntities.CompaniesShareHoldersGroup", b =>
                {
                    b.Property<int>("CompaniesShareHoldersGroupIdn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CompaniesShareHoldersGroupIDN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompaniesShareHoldersGroupIdn"));

                    b.Property<int>("CompaniesIdn")
                        .HasColumnType("int")
                        .HasColumnName("Companies_IDN");

                    b.Property<string>("CompaniesShareHoldersGroupIdc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CompaniesShareHoldersGroupIDC");

                    b.Property<DateTime>("CreatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedBy_Date");

                    b.Property<int>("CreatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy_IDN");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy_Name");

                    b.Property<bool>("ShareHolderGroupActive")
                        .HasColumnType("bit")
                        .HasColumnName("ShareHolderGroupActive");

                    b.Property<DateTime>("ShareHolderGroupDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ShareHolderGroupDate");

                    b.Property<DateTime?>("UpdatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedBy_Date");

                    b.Property<int?>("UpdatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("UpdatedBy_IDN");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy_Name");

                    b.HasKey("CompaniesShareHoldersGroupIdn");

                    b.ToTable("CompaniesShareHoldersGroups");
                });

            modelBuilder.Entity("Nexus.LAS.Domain.Entities.CompanyEntities.Company", b =>
                {
                    b.Property<int>("CompanyIdn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyIdn"));

                    b.Property<decimal?>("CapitalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("CciExpiryActiveReminder")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CciExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CciIssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CciNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompanyArabicName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyClass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompanyClassIdn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompanyEnglishName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyIdc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompanyShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompanyStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CompanyTypeIdn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedBy_Date");

                    b.Property<int>("CreatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy_IDN");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy_Name");

                    b.Property<string>("GroupCompany")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("IncorporationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LegalType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("NumberOfPartners")
                        .HasColumnType("int");

                    b.Property<int?>("PersonsIdn")
                        .HasColumnType("int")
                        .HasColumnName("Persons_IDN");

                    b.Property<string>("PlaceOfRegistrationMain")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlaceOfRegistrationMainIdn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlaceOfRegistrationSub")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PlaceOfRegistrationSubIdn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Private")
                        .HasColumnType("bit");

                    b.Property<string>("RelevantCompany")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long?>("TotalShares")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateDescription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedBy_Date");

                    b.Property<int?>("UpdatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("UpdatedBy_IDN");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy_Name");

                    b.HasKey("CompanyIdn");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Nexus.LAS.Domain.Entities.Lookup.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .HasColumnType("int")
                        .HasColumnName("CountryId");

                    b.Property<string>("Capital")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Capital");

                    b.Property<string>("CountryName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("CountryName");

                    b.Property<string>("Currency")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Currency");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CurrencyCode");

                    b.Property<string>("FIPS104")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FIPS104");

                    b.Property<string>("ISO2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ISO2");

                    b.Property<string>("ISO3")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ISO3");

                    b.Property<string>("ISON")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ISON");

                    b.Property<string>("Internet")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Internet");

                    b.Property<string>("MapReference")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("MapReference");

                    b.Property<string>("NationalityPlural")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("NationalityPlural");

                    b.Property<string>("NationalitySingular")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("NationalitySingular");

                    b.Property<string>("Population")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Population");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Title");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Nexus.LAS.Domain.Entities.Lookup.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlphabeticCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("AlphabeticCode");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Currency");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Entity");

                    b.Property<bool>("IsFundYesNo")
                        .HasColumnType("bit")
                        .HasColumnName("IsFundYesNo");

                    b.Property<string>("MinorUnit")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("MinorUnit");

                    b.Property<string>("NumericCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("NumericCode");

                    b.HasKey("Id");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("Nexus.LAS.Domain.Entities.Lookup.DynamicList", b =>
                {
                    b.Property<string>("DynamicListIdC")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DynamicListIDC");

                    b.Property<int>("DynamicListIdN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DynamicListIDN");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DynamicListIdN"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit")
                        .HasColumnName("Active");

                    b.Property<DateTime>("CreatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedBy_Date");

                    b.Property<int>("CreatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy_IDN");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy_Name");

                    b.Property<string>("LinkedCategory")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LinkedCategory");

                    b.Property<int?>("MainListID")
                        .HasColumnType("int")
                        .HasColumnName("MainListID");

                    b.Property<string>("MenuCategory")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MenuCategory");

                    b.Property<string>("MenuValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MenuValue");

                    b.Property<int?>("Rank")
                        .HasColumnType("int")
                        .HasColumnName("Rank");

                    b.Property<DateTime?>("UpdatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedBy_Date");

                    b.Property<int?>("UpdatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("UpdatedBy_IDN");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy_Name");

                    b.HasKey("DynamicListIdC", "DynamicListIdN");

                    b.ToTable("DynamicLists");
                });

            modelBuilder.Entity("Nexus.LAS.Domain.Entities.Lookup.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedBy_Date");

                    b.Property<int>("CreatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy_IDN");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy_Name");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Description");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("GroupName");

                    b.Property<DateTime?>("UpdatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedBy_Date");

                    b.Property<int?>("UpdatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("UpdatedBy_IDN");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy_Name");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Nexus.LAS.Domain.Entities.Lookup.GroupMenu", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("GroupID")
                        .HasColumnOrder(0);

                    b.Property<int>("MenuId")
                        .HasColumnType("int")
                        .HasColumnName("MenuID")
                        .HasColumnOrder(1);

                    b.Property<int?>("Access")
                        .HasColumnType("int")
                        .HasColumnName("Access");

                    b.Property<int?>("Admin")
                        .HasColumnType("int")
                        .HasColumnName("Admin");

                    b.Property<int?>("CanDelete")
                        .HasColumnType("int")
                        .HasColumnName("CanDelete");

                    b.Property<int?>("CanInsert")
                        .HasColumnType("int")
                        .HasColumnName("CanInsert");

                    b.Property<int?>("CanUpdate")
                        .HasColumnType("int")
                        .HasColumnName("CanUpdate");

                    b.HasKey("GroupId", "MenuId");

                    b.HasIndex("MenuId");

                    b.ToTable("GroupsMenus");
                });

            modelBuilder.Entity("Nexus.LAS.Domain.Entities.Lookup.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedBy_Date");

                    b.Property<int>("CreatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy_IDN");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreatedBy_Name");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("ParentID");

                    b.Property<string>("Path")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Path");

                    b.Property<int?>("Rank")
                        .HasColumnType("int")
                        .HasColumnName("Rank");

                    b.Property<DateTime?>("UpdatedByDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedBy_Date");

                    b.Property<int?>("UpdatedByIdN")
                        .HasColumnType("int")
                        .HasColumnName("UpdatedBy_IDN");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UpdatedBy_Name");

                    b.HasKey("Id");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("Nexus.LAS.Domain.Entities.NumberEntities.Number", b =>
                {
                    b.Property<int>("NumberValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumberValue"));

                    b.HasKey("NumberValue");

                    b.ToTable("Numbers");
                });

            modelBuilder.Entity("Nexus.LAS.Domain.Entities.Lookup.GroupMenu", b =>
                {
                    b.HasOne("Nexus.LAS.Domain.Entities.Lookup.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nexus.LAS.Domain.Entities.Lookup.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Menu");
                });
#pragma warning restore 612, 618
        }
    }
}
